force-app/main/default/objects/WAMessage__c/WAMessage__c.object-meta.xml
<CustomObject>
    <label>WA Message</label>
    <nameField>
        <displayFormat>WA-{0000}</displayFormat>
        <label>WA Message ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WA Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WAMessage__c/fields/AgentName__c.field-meta.xml
<CustomField>
    <fullName>AgentName__c</fullName>
    <label>AgentName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/BusinessPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>BusinessPhoneNumber__c</fullName>
    <label>Business Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/MessageContent__c.field-meta.xml
<CustomField>
    <fullName>MessageContent__c</fullName>
    <label>Message Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/MessageController.cls
public class MessageController {
 // This method fetches a list of WA_Message__c records.
    @AuraEnabled(cacheable=true)
    public static List<WAMessage__c> getMessages() {
        // Query the WA_Message__c object to retrieve the required fields.
        return [
            SELECT  Name,AgentName__c, BusinessPhoneNumber__c, MessageContent__c,
                   CreatedBy.Name, CustomerName__c, CustomerPhone__c,
                   Message_Sent_Time__c
            FROM WAMessage__c
            ORDER BY Message_Sent_Time__c DESC  // Get the most recent messages first.
            LIMIT 10  
        ];
    }
}