force-app/main/default/objects/WAMessage__c/WAMessage__c.object-meta.xml
<CustomObject>
    <label>WA Message</label>
    <nameField>
        <displayFormat>WA-{0000}</displayFormat>
        <label>WA Message ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WA Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WAMessage__c/fields/AgentName__c.field-meta.xml
<CustomField>
    <fullName>AgentName__c</fullName>
    <label>AgentName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/BusinessPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>BusinessPhoneNumber__c</fullName>
    <label>Business Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/ImageSHA256__c.field-meta.xml
<CustomField>
    <fullName>ImageSHA256__c</fullName>
    <label>ImageSHA256</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/Is_Seen__c.field-meta.xml
<CustomField>
    <fullName>Is_Seen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Seen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/MessageContent__c.field-meta.xml
<CustomField>
    <fullName>MessageContent__c</fullName>
    <label>Message Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/Reaction__c.field-meta.xml
<CustomField>
    <fullName>Reaction__c</fullName>
    <label>Reaction</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/message.cls
public with sharing class message{
    
    @AuraEnabled(cacheable=true)
    public static List<WAMessage__c> getMessages() {
        return [SELECT  AgentName__c, BusinessPhoneNumber__c, MessageContent__c,
CreatedBy.Name, CustomerName__c, CustomerPhone__c, Image_ID__c, Image_Type__c,ImageSHA256__c,Message_ID__c,Message_Sent_Time__c,Message_Type__c,Outgoing__c,Parent_Message_ID__c,Reaction__c,Is_Seen__c
                FROM WAMessage__c WHERE Is_Seen__c= false
                ORDER BY Message_Sent_Time__c DESC
                LIMIT 10];
    }
}