force-app/main/default/objects/WAMessage__c/WAMessage__c.object-meta.xml
<CustomObject>
    <label>WA Message</label>
    <nameField>
        <displayFormat>WA-{0000}</displayFormat>
        <label>WA Message ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WA Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WAMessage__c/fields/AgentName__c.field-meta.xml
<CustomField>
    <fullName>AgentName__c</fullName>
    <label>AgentName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/BusinessPhoneNumber__c.field-meta.xml
<CustomField>
    <fullName>BusinessPhoneNumber__c</fullName>
    <label>Business Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/ImageSHA256__c.field-meta.xml
<CustomField>
    <fullName>ImageSHA256__c</fullName>
    <label>ImageSHA256</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/Is_Seen__c.field-meta.xml
<CustomField>
    <fullName>Is_Seen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Seen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/MessageContent__c.field-meta.xml
<CustomField>
    <fullName>MessageContent__c</fullName>
    <label>Message Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WAMessage__c/fields/Reaction__c.field-meta.xml
<CustomField>
    <fullName>Reaction__c</fullName>
    <label>Reaction</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MessageTest.cls
@isTest
public class MessageTest {
    
    @testSetup
    static void setup() {
        // Create test data
        List<WAMessage__c> messages = new List<WAMessage__c>();
        for (Integer i = 0; i < 15; i++) {
            WAMessage__c message = new WAMessage__c(
                AgentName__c = 'Test Agent ' + i,
                BusinessPhoneNumber__c = '1234567890',
                MessageContent__c = 'This is a test message ' + i,
                //CreatedById = UserInfo.getUserId(),
                CustomerName__c = 'Test Customer ' + i,
                CustomerPhone__c = '0987654321',
                Image_ID__c = 'ImageID' + i,
                Image_Type__c = 'ImageType' + i,
                ImageSHA256__c = 'SHA256' + i,
                Message_ID__c = 'MessageID' + i,
                Message_Sent_Time__c = System.now().addMinutes(-i),
                Message_Type__c = 'text',
                Outgoing__c = false,
                Parent_Message_ID__c = 'ParentMessageID' + i,
                Reaction__c = 'Reaction' + i,
                Is_Seen__c = false
            );
            messages.add(message);
        }
        insert messages;
    }
    
    @isTest
    static void testGetMessages() {
        Test.startTest();
        List<WAMessage__c> messages = message.getMessages();
        Test.stopTest();
        
        System.assertEquals(10, messages.size(), 'Expected 10 messages to be returned');
        for (WAMessage__c msg : messages) {
            System.assertEquals(false, msg.Is_Seen__c, 'Expected Is_Seen__c to be false');
        }
    }
}